version: "3.9"
services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"

  route_service:
    build: ./route_service
    container_name: route_service
    ports:
      - "8001:8000"
